### ISSUE TITLE
call to _.template causes a Content-Security-Policy violation

### ISSUE THREAD

**Issue by ctemplin** [wyuenho/backgrid#434]
If using a strcit CSP e.g. "default-src 'self';", a violation is throw when the backgrid script is loaded.

Here's the change I've applied for use in my project. Note, I have not thoroughly tested this with non-CSP sites.

https://github.com/ctemplin/backgrid/commit/83af5fbab62578f08ad657c3ae8f7c0b2bf70c56

thanks

**Comment by matts1189** [comment]
Hi, I'm running 1.8.3 but am still getting this error in the m.template function: 

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Called via:
 this.template = _.template($('#tpl-activity-line').html());

If I add the unsafe-eval (which I really really don't want to do) then everything works.
