### ISSUE TITLE
Backgrid Footer

### ISSUE THREAD

**Issue by cime** [wyuenho/backgrid#439]
Footer is now rendered before Body. It should be like this:
1. Header
2. Body
3. Footer

It would be nice to be able to insert footer after the _table_ tag, otherwise footer is inserted inside _table_ tag which on many occasions is not good for a pager. For this it would be neccessary to wrap the whole grid into a div, because you can't call .after instead of .append in the element is not placed into DOM.

https://github.com/wyuenho/backgrid/blob/master/lib/backgrid.js#L2856

**Comment by lzrski** [comment]
Hi.

@wyuenho: Thanks for explaining. It seems that in HTML5 this order is no longer mandatory:

> It can be before or after all `<tbody>` and `<tr>` elements, but not intermixed with them.
>
> `HTML 4` The `<tfoot>` element cannot be placed after any `<tbody>` and `<tr>` element. This restriction has been softened in `HTML5`.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot#Usage_context

I ran into following problem. In order to be displayed below table body, footer's CSS `display` property must be set to `table-footer-group`. In print some browsers (eg Firefox and IE11) repeat such elements on every page. In my use case I would like to avoid that - my footer sometimes contains a lot of rows with aggregated data.

It would be easy to work around if a footer is placed after table body. I would then just set it's `display` to `table-row-group`.

Any ideas how to go about that?

BTW, I absolutely love Backgrid. It really shows the power and flexibility of Backbone :)
