### ISSUE TITLE
Event fire after grid rendered

### ISSUE THREAD

**Issue by sameercaresu** [wyuenho/backgrid#556]
I am using backgrid with backbone pageable/paginator.

I am trying to add some css classes once the grid is rendered and is in the DOM.

So, what event gets fired once grid has been fully rendered also accounting for paging( or on each added row).
[link to similar stackoverflow question](http://stackoverflow.com/questions/28106510/how-to-fire-event-on-backgrid-row-add)

**Comment by vesper8** [comment]
i am having a problem with this as well.

I am trying to do something as simple as only showing the paginator if the returned resultSet is larger than the pageSize, and this is proving quite difficult because by the time the backgrid:rendered is fired the pageableGrid.collection.state.totalRecords (or pageableGrid.collection.length for that matter) have not yet been updated!

If I had a timeout of 100ms inside the backgrid:rendered callback then the totalRecords is populated most of the time. This is horrible practice needless to say. Is there another event I can listen to that is only triggered once the collection.state has been updated? I am using the server mode.

Also.. is there any chance of a new release? I really like backgrid but would feel much better if I knew it was getting updated to use more recent dependendies and all that.

Please let me know if there's another way (a better way) of getting the number of records by using the right event. Thanks

**Comment by Devtr0n** [comment]
I am in a similar situation. document.ready() fires, but the backgrid is not rendered yet.

I am unsure what to do. I do not know how to "hook" into the completion event of backgrid? Help?

**Comment by wyuenho** [comment]
@sameercaresu There's no event fired when a grid is done rendering. Since you have to call render manually, you know exactly when it'll be done rendering. At which point you can just use your do your usual jQuery magic to manipulate the CSS classes.

@vesper8 When you fetch from a collection. Backbone.Collection will fire a `sync` event when the fetch was successful.

http://backbonejs.org/#Events-catalog
