### ISSUE TITLE
new release as needed from bower?

### ISSUE THREAD

**Issue by sameercaresu** [wyuenho/backgrid#567]
Hi, it would be nice to have a new release as there are new changes(especially in backgrid pagination and backgrid amd) and its been a while since last release.

**Comment by soulso** [comment]
+1

**Comment by vesper8** [comment]
yes please

**Comment by Matheo13** [comment]
+1

**Comment by kiRach** [comment]
:+1:

**Comment by ttyusupov** [comment]
+100

**Comment by ambischof** [comment]
+1 pretty please?

**Comment by rockerest** [comment]
+1 - pointing npm directly to the Github repo to get the latest code; highly volatile solution when the repository should just be tagged and released.

**Comment by AlJohri** [comment]
@rockerest I'm using `"backgrid": "git+https://github.com/wyuenho/backgrid.git#0.3.5"` in my package.json for npm. Would be great to have an official bower/npm package but not too volatile given the nicely tagged releases.

**Comment by rockerest** [comment]
@AlJohri I think you may have misunderstood: I can get 0.3.5 from NPM directly, no problem there (`npm install backgrid`) the problem is [these changes](https://github.com/wyuenho/backgrid/compare/0.3.5...master) that aren't tagged and represent a significant body of (stable) work.

As the OP @sameercaresu states, there have been significant improvements like to AMD support, upgrading libraries (underscore, backbone, pageable collections, etc.) that the casual puveyor would not get. Only those following the library (or encountering major functionality issues) would know to grab the latest directly from the `.git`, and by that time your average developer will have looked elsewhere. It's a disservice to the library to have not tagged it for almost two years.

I've tagged my own libraries before. It takes 60 seconds. I'd be happy to do it if I had repo access. I can't dedicate any time as full "maintainer" but I'd be happy to create tags as necessary. This feels necessary.

**Comment by AlJohri** [comment]
Ah I misunderstood. Thanks for clarifying

**Comment by wyuenho** [comment]
It's been released some time ago.
